### ISSUE TITLE
Cannot download pretrained model

### ISSUE THREAD

**Issue by NidhiBharani** [kaiidams/Kokoro-Speech-Dataset#13]
Hi, I got to know about your work through this discussion thread in coquiTTS : https://github.com/coqui-ai/TTS/discussions/930 and found your dataset included in TTS/recipes as well. I am interested in Japanese TTS as well so thanks for sharing your work!

### Description
I tried to download the pretrained model but the link doesn't seem to be working. I am attaching a screenshot.
![Screenshot from 2022-05-07 21-41-16](https://user-images.githubusercontent.com/23429320/167263167-9f1a1dc6-441e-4536-97b0-eb87abc7b1d4.png)

### Steps to reproduce error

1. Tried wget: `wget https://github.com/kaiidams/Kokoro-Speech-Dataset/releases/download/1.0/tacotron-kokoro-20210324.zip`
2. Also searched through all releases and tags.

**Comment by kaiidams** [comment]
@NidhiBharani
Added the pretrained model to `https://github.com/kaiidams/Kokoro-Speech-Dataset/releases/download/1.0/tacotron-kokoro-20210324.zip`.

The model is based on Tacotron 1 + TensorFlow 1.x and the model is not trained long enough. If you are looking for newer model, you can look at this recipe https://github.com/coqui-ai/TTS/tree/main/recipes/kokoro/tacotron2-DDC. Coqui-TTS has a Kokoro model with Tacotron 2 + HiFi GAN.

**Comment by kaiidams** [comment]
Download link is correct now.
